services:
  iam-dev:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.develop
      target: STANDARD
    entrypoint: /bin/sh -c './server --createDatabase=true'
    extra_hosts:
      - "iam-dev.hanzo.ai:host-gateway"
      - "172.17.0.1:host-gateway"
    depends_on:
      - iam-dev-db
      - redis-iam-dev
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./conf/app.dev.conf:/conf/app.conf
    tmpfs:
      - /tmp:exec,mode=1777
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.well-known.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.iam-csp.headers.customResponseHeaders.Content-Security-Policy=connect-src 'self' https://iam-dev.hanzo.ai http://iam-dev.hanzo.ai;"
      - "traefik.http.routers.iam-http.rule=Host(`iam-dev.hanzo.ai`)"
      - "traefik.http.routers.iam-http.entrypoints=web"
      - "traefik.http.routers.iam-http.middlewares=well-known,iam-csp,redirect-to-https"
      - "traefik.http.routers.iam-https.rule=Host(`iam-dev.hanzo.ai`)"
      - "traefik.http.routers.iam-https.entrypoints=websecure"
      - "traefik.http.routers.iam-https.middlewares=well-known,iam-csp"
      - "traefik.http.routers.iam-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.iam.loadbalancer.server.port=8000"
    networks:
      - hanzo-network
      - internal-dev-iam
  iam-dev-db:
    restart: always
    # image: mysql
    image: mysql:8.0.25
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    volumes:
      - iam-dev-db:/var/lib/mysql
    networks:
      - internal-dev-iam
  redis-iam-dev:
    restart: always
    image: redis:7-alpine
    volumes:
      - iam-dev-redis:/data
    networks:
      - internal-dev-iam

volumes:
  iam-dev-db:
    name: iam-dev-db-volume
  iam-dev-redis:
    driver: local

networks:
  internal-dev-iam:
  hanzo-network:
    external: true
